package installer

import (
	"fmt"
	"strconv"
	"strings"
)

func renderSysusers() string {
	return `# Generated by dirextalk-knowledge-installer; do not edit.
g dirextalk-worker -
u dirextalk-qdrant - "Dirextalk Qdrant" /var/lib/dirextalk-knowledge/qdrant
u dirextalk-knowledge - "Dirextalk Knowledge Adapter" /var/lib/dirextalk-knowledge/adapter
m dirextalk-knowledge dirextalk-worker
`
}

func renderTmpfiles() string {
	return `# Generated by dirextalk-knowledge-installer; do not edit.
d /run/dirextalk-knowledge 0750 dirextalk-knowledge dirextalk-worker -
d /var/lib/dirextalk-knowledge/qdrant/storage 0750 dirextalk-qdrant dirextalk-qdrant -
d /var/lib/dirextalk-knowledge/adapter 0750 dirextalk-knowledge dirextalk-knowledge -
`
}

func renderQdrantConfig(apiKey string) (string, error) {
	if !validAPIKey(apiKey) {
		return "", fmt.Errorf("invalid fixed Qdrant API key")
	}
	return `storage:
  storage_path: /var/lib/dirextalk-knowledge/qdrant/storage
service:
  host: 127.0.0.1
  http_port: 6333
  grpc_port: null
  enable_cors: false
  enable_tls: true
  verify_https_client_certificate: false
  max_request_size_mb: 2
  api_key: ` + strconv.Quote(apiKey) + `
cluster:
  enabled: false
telemetry_disabled: true
tls:
  cert: /var/lib/dirextalk-knowledge/tls/qdrant.crt
  key: /var/lib/dirextalk-knowledge/tls/qdrant.key
`, nil
}

func renderQdrantUnit() string {
	return `[Unit]
Description=Dirextalk retained Knowledge Qdrant
After=local-fs.target
Before=dirextalk-knowledge-adapter.service

[Service]
Type=simple
User=dirextalk-qdrant
Group=dirextalk-qdrant
ExecStart=/opt/dirextalk/knowledge/current/qdrant --config-path /etc/dirextalk-knowledge/qdrant.yaml
Restart=on-failure
RestartSec=2s
UMask=0077
NoNewPrivileges=true
PrivateTmp=true
PrivateDevices=true
ProtectSystem=strict
ProtectHome=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
ProtectClock=true
RestrictSUIDSGID=true
LockPersonality=true
RestrictRealtime=true
SystemCallArchitectures=native
RestrictAddressFamilies=AF_UNIX AF_INET
IPAddressDeny=any
IPAddressAllow=localhost
ReadWritePaths=/var/lib/dirextalk-knowledge/qdrant
ReadOnlyPaths=/var/lib/dirextalk-knowledge/tls /etc/dirextalk-knowledge/qdrant.yaml

[Install]
WantedBy=multi-user.target
`
}

func renderAdapterUnit() string {
	return `[Unit]
Description=Dirextalk retained Knowledge adapter
Requires=dirextalk-qdrant.service
After=dirextalk-qdrant.service

[Service]
Type=simple
User=dirextalk-knowledge
Group=dirextalk-knowledge
SupplementaryGroups=dirextalk-worker
ExecStart=/usr/bin/python3.12 -I -S -B /opt/dirextalk/knowledge/current/adapter/main.py
Restart=on-failure
RestartSec=2s
UMask=0077
NoNewPrivileges=true
PrivateTmp=true
PrivateDevices=true
ProtectSystem=strict
ProtectHome=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
ProtectClock=true
RestrictSUIDSGID=true
LockPersonality=true
RestrictRealtime=true
SystemCallArchitectures=native
RestrictAddressFamilies=AF_UNIX AF_INET
IPAddressDeny=any
IPAddressAllow=localhost
ReadWritePaths=/var/lib/dirextalk-knowledge/adapter /run/dirextalk-knowledge
ReadOnlyPaths=/opt/dirextalk/knowledge /var/lib/dirextalk-knowledge/tls /var/lib/dirextalk-knowledge/secrets

[Install]
WantedBy=multi-user.target
`
}

func validAPIKey(value string) bool {
	if len(value) < 32 || len(value) > 256 || strings.TrimSpace(value) != value {
		return false
	}
	for _, character := range value {
		if !(character >= 'a' && character <= 'z') && !(character >= 'A' && character <= 'Z') && !(character >= '0' && character <= '9') && character != '_' && character != '-' {
			return false
		}
	}
	return true
}
