package postgres

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"testing"
	"time"
	"unsafe"

	"github.com/YingSuiAI/dirextalk-agent/internal/cloudworker"
	"github.com/YingSuiAI/dirextalk-agent/internal/coreconfirmation"
	"github.com/YingSuiAI/dirextalk-agent/internal/coretask"
	"github.com/google/uuid"
)

// These fixtures were captured by the actual released source at the commits
// named in each file, including its marshal->scan->frozen-binding path. They
// are deliberately not generated by the compatibility implementation.
type releasedCloudWorkerFixture struct {
	Release             string                     `json:"release"`
	SourceCommit        string                     `json:"source_commit"`
	Variant             string                     `json:"variant"`
	PublicPlan          json.RawMessage            `json:"public_plan"`
	PrivatePlan         json.RawMessage            `json:"private_plan"`
	Execution           cloudworker.Execution      `json:"execution"`
	ConfirmationBinding coreconfirmation.Binding   `json:"confirmation_binding"`
	StoredColumns       releasedCloudWorkerColumns `json:"stored_columns"`
}

type releasedCloudWorkerColumns struct {
	Revision                 uint64 `json:"revision"`
	CredentialRevision       uint64 `json:"credential_revision"`
	Digest                   string `json:"digest"`
	ExecutionDigest          string `json:"execution_digest"`
	AuthorizationBasisDigest string `json:"authorization_basis_digest"`
	QuoteDigest              string `json:"quote_digest"`
	InputManifestDigest      string `json:"input_manifest_digest"`
	ModelBindingDigest       string `json:"model_binding_digest"`
	CredentialID             string `json:"credential_id"`
}

type releasedCloudWorkerRow struct{ fixture releasedCloudWorkerFixture }

func (row releasedCloudWorkerRow) Scan(dest ...any) error {
	if len(dest) != 11 {
		return errors.New("unexpected released fixture scan")
	}
	columns := row.fixture.StoredColumns
	*dest[0].(*[]byte), *dest[1].(*[]byte) = row.fixture.PublicPlan, row.fixture.PrivatePlan
	*dest[2].(*int64) = int64(columns.Revision)
	*dest[3].(*string), *dest[4].(*string), *dest[5].(*string) = columns.Digest, columns.ExecutionDigest, columns.AuthorizationBasisDigest
	*dest[6].(*string), *dest[7].(*string), *dest[8].(*string) = columns.QuoteDigest, columns.InputManifestDigest, columns.ModelBindingDigest
	*dest[9].(*string), *dest[10].(*int64) = columns.CredentialID, int64(columns.CredentialRevision)
	return nil
}

func loadReleasedCloudWorkerFixture(t *testing.T, name string) releasedCloudWorkerFixture {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatal(err)
	}
	var fixture releasedCloudWorkerFixture
	if err = json.Unmarshal(raw, &fixture); err != nil {
		t.Fatal(err)
	}
	if fixture.Release == "" || fixture.SourceCommit == "" || fixture.Variant == "" {
		t.Fatalf("incomplete fixture %q", name)
	}
	return fixture
}

func TestScanCloudWorkerPlanAcceptsReleasedGitHubDigestEncodings(t *testing.T) {
	legacy := loadReleasedCloudWorkerFixture(t, "v184-unbound.json")
	deployed := loadReleasedCloudWorkerFixture(t, "v185-unbound.json")
	bound := loadReleasedCloudWorkerFixture(t, "v185-bound.json")

	plans := make(map[string]cloudworker.Plan, 3)
	for name, fixture := range map[string]releasedCloudWorkerFixture{"v184": legacy, "v185-unbound": deployed, "v185-bound": bound} {
		plan, err := scanCloudWorkerPlan(releasedCloudWorkerRow{fixture: fixture})
		if err != nil {
			t.Fatalf("%s source=%s scan: %v", name, fixture.SourceCommit, err)
		}
		if err = cloudworker.ValidateFrozenBinding(plan, fixture.Execution, fixture.ConfirmationBinding); err != nil {
			t.Fatalf("%s source=%s frozen confirmation: %v", name, fixture.SourceCommit, err)
		}
		plans[name] = plan
	}
	if plans["v184"].IsV185NilGitHubEncoding() || !plans["v185-unbound"].IsV185NilGitHubEncoding() ||
		plans["v185-bound"].IsV185NilGitHubEncoding() || plans["v185-bound"].GitHubBinding == nil {
		t.Fatalf("unexpected released encoding selection: v184=%v v185=%v bound=%+v", plans["v184"].IsV185NilGitHubEncoding(), plans["v185-unbound"].IsV185NilGitHubEncoding(), plans["v185-bound"].GitHubBinding)
	}

}

// markReleasedV185Unbound is test-only plumbing for converting a linked
// current harness row to the deployed encoding. The frozen fixtures above
// independently prove the exact source encoding; this only drives the real
// PostgreSQL confirmation, queue, and replay consumers with matching IDs.
func markReleasedV185Unbound(t *testing.T, plan *cloudworker.Plan) {
	t.Helper()
	setReleasedV185UnboundFlag(t, plan, true)
	// Seal computes the old v185 authorization basis before it rejects the old
	// quote basis. Re-seal the quote, then complete the historical plan seal.
	_ = plan.Seal()
	plan.Quote.BasisDigest = plan.AuthorizationBasisDigest
	if err := plan.Quote.Seal(); err != nil {
		t.Fatal(err)
	}
	if err := plan.Seal(); err != nil {
		t.Fatal(err)
	}
}

func setReleasedV185UnboundFlag(t *testing.T, plan *cloudworker.Plan, value bool) {
	t.Helper()
	field := reflect.ValueOf(plan).Elem().FieldByName("v185NilGitHubDigest")
	if !field.IsValid() || field.Kind() != reflect.Bool || !field.CanAddr() {
		t.Fatal("cloud worker v185 test marker unavailable")
	}
	reflect.NewAt(field.Type(), unsafe.Pointer(field.UnsafeAddr())).Elem().SetBool(value)
}

func releasedProposalReplayDigests(t *testing.T, deployed cloudworker.Plan, requirements cloudworker.ComputeRequirements) (string, string) {
	t.Helper()
	legacy := deployed
	setReleasedV185UnboundFlag(t, &legacy, false)
	_ = legacy.Seal()
	legacy.Quote.BasisDigest = legacy.AuthorizationBasisDigest
	if err := legacy.Quote.Seal(); err != nil {
		t.Fatal(err)
	}
	if err := legacy.Seal(); err != nil {
		t.Fatal(err)
	}
	digest := func(plan cloudworker.Plan, github any) string {
		raw, _ := json.Marshal(struct {
			OwnerID, ConversationID, TurnID, Objective, UserPromptDigest, InputManifestDigest, ModelBindingDigest, AuthorizationBasisDigest string
			GitHubBinding                                                                                                                   any `json:",omitempty"`
			AccountGeneration                                                                                                               uint64
			ProposalReason                                                                                                                  cloudworker.ProposalReason
			BudgetEvidence                                                                                                                  *cloudworker.LocalBudgetEvidence
			WorkspaceMode                                                                                                                   cloudworker.WorkspaceMode
			ComputeRequirements                                                                                                             cloudworker.ComputeRequirements
		}{plan.OwnerID, plan.ConversationID, plan.TurnID, plan.Objective, plan.UserPromptDigest, plan.InputManifestDigest, plan.ModelAuthorization.BindingDigest, plan.AuthorizationBasisDigest, github, plan.AccountGeneration, plan.ProposalReason, plan.LocalBudgetEvidence, plan.WorkspaceMode, requirements})
		sum := sha256.Sum256(raw)
		return hex.EncodeToString(sum[:])
	}
	return digest(legacy, nil), digest(deployed, (*cloudworker.GitHubBinding)(nil))
}

func TestCloudWorkerPostgresReplaysAndRunsDeployedV185UnboundOffer(t *testing.T) {
	h := newPGCloudWorkerHarness(t)
	defer h.cleanup()
	offer := h.propose(t)
	plan := offer.Plan
	markReleasedV185Unbound(t, &plan)
	execution, err := cloudworker.NewExecution(plan)
	if err != nil {
		t.Fatal(err)
	}
	binding, err := cloudworker.BindingForPlan(plan)
	if err != nil {
		t.Fatal(err)
	}
	planRaw, privateRaw, err := marshalCloudWorkerPlan(plan)
	if err != nil {
		t.Fatal(err)
	}
	executionRaw, err := marshalCloudWorkerExecution(execution)
	if err != nil {
		t.Fatal(err)
	}
	bindingRaw, _ := json.Marshal(binding)
	var payloadRaw []byte
	if err = h.store.pool.QueryRow(h.ctx, `SELECT payload_json FROM core_tasks WHERE task_id=$1`, offer.Task.ID).Scan(&payloadRaw); err != nil {
		t.Fatal(err)
	}
	var payload coretask.TaskPayload
	if err = json.Unmarshal(payloadRaw, &payload); err != nil || payload.CloudWorker == nil {
		t.Fatalf("payload=%s err=%v", payloadRaw, err)
	}
	payload.CloudWorker.PlanDigest, payload.CloudWorker.ExecutionDigest, payload.CloudWorker.QuoteDigest = plan.Digest, plan.ExecutionDigest, plan.Quote.Digest
	payloadRaw, _ = json.Marshal(payload)
	for _, update := range []struct {
		query string
		args  []any
	}{
		{`UPDATE core_cloud_worker_plans SET digest=$2,execution_digest=$3,authorization_basis_digest=$4,quote_digest=$5,plan_json=$6,private_json=$7 WHERE plan_id=$1`, []any{plan.PlanID, plan.Digest, plan.ExecutionDigest, plan.AuthorizationBasisDigest, plan.Quote.Digest, planRaw, privateRaw}},
		{`UPDATE core_cloud_worker_executions SET plan_digest=$2,execution_digest=$3,digest=$4,execution_json=$5 WHERE execution_id=$1`, []any{execution.ExecutionID, execution.PlanDigest, execution.ExecutionDigest, execution.Digest, executionRaw}},
		{`UPDATE core_tasks SET payload_json=$2 WHERE task_id=$1`, []any{offer.Task.ID, payloadRaw}},
		{`UPDATE core_confirmations SET binding_json=$2 WHERE confirmation_id=$1`, []any{plan.ConfirmationID, bindingRaw}},
		{`UPDATE core_confirmation_target_bindings SET binding_json=$2 WHERE confirmation_id=$1`, []any{plan.ConfirmationID, bindingRaw}},
		{`UPDATE core_confirmation_current_bindings SET binding_json=$3 WHERE operation_domain=$1 AND target_id=$2`, []any{cloudworker.OperationDomain, plan.ExecutionID, bindingRaw}},
	} {
		if _, err = h.store.pool.Exec(h.ctx, update.query, update.args...); err != nil {
			t.Fatal(err)
		}
	}
	legacyDigest, deployedDigest := releasedProposalReplayDigests(t, plan, h.command.ComputeRequirements)
	if legacyDigest == deployedDigest || deployedDigest == "" {
		t.Fatalf("invalid replay candidates legacy=%q deployed=%q", legacyDigest, deployedDigest)
	}
	if _, err = h.store.pool.Exec(h.ctx, `UPDATE core_cloud_worker_offer_replays SET request_digest=$2 WHERE plan_id=$1`, plan.PlanID, deployedDigest); err != nil {
		t.Fatal(err)
	}
	// Propose emits the restored v184 digest. CreateOffer must recognize only
	// this plan's exact v185 alternate, load it through the scanner, and replay.
	replayed, err := h.service.Propose(h.ctx, h.command)
	if err != nil || !replayed.Plan.IsV185NilGitHubEncoding() {
		t.Fatalf("replay plan=%+v err=%v", replayed.Plan, err)
	}
	confirmationService, err := coreconfirmation.NewService(h.confirmations)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = confirmationService.Confirm(h.ctx, coreconfirmation.ConfirmCommand{ConfirmationID: plan.ConfirmationID, IdempotencyKey: uuid.NewString(), ExpectedRevision: offer.Confirmation.Revision, At: h.now}); err != nil {
		t.Fatal(err)
	}
	running, _, err := NewCoreTaskStore(h.store).ClaimNextDue(h.ctx, "released-v185", h.now, 2*time.Minute, 1)
	if err != nil {
		t.Fatal(err)
	}
	sshStore, err := NewSSHWorkerStore(h.store, "cloud-worker/artifacts")
	if err != nil {
		t.Fatal(err)
	}
	if _, err = sshStore.Begin(h.ctx, running); err != nil {
		t.Fatal(err)
	}
}
